let districtsList=[
    {name: "Barguna", code: "BA"},
    {name: "Barishal", code: "BR"},
    {name: "Bhola", code: "BH"},
    {name: "Jhalokati", code: "JL"},
    {name: "Patuakhali", code: "PT"},
    {name: "Pirojpur", code: "PI"},
    {name: "Bandarban", code: "BN"},
    {name: "Brahmanbaria", code: "BB"},
    {name: "Chandpur", code: "CP"},
    {name: "Chattogram", code: "CH"},
    {name: "Cumilla", code: "CU"},
    {name: "Cox's Bazar", code: "CX"},
    {name: "Feni", code: "FN"},
    {name: "Khagrachhari", code: "KC"},
    {name: "Lakshmipur", code: "LK"},
    {name: "Noakhali", code: "NO"},
    {name: "Rangamati", code: "RM"},
    {name: "Dhaka", code: "DH"},
    {name: "Faridpur", code: "FR"},
    {name: "Gazipur", code: "GZ"},
    {name: "Gopalganj", code: "GG"},
    {name: "Kishoreganj", code: "KS"},
    {name: "Madaripur", code: "MD"},
    {name: "Manikganj", code: "MG"},
    {name: "Munshiganj", code: "MN"},
    {name: "Narayanganj", code: "NR"},
    {name: "Narsingdi", code: "NA"},
    {name: "Rajbari", code: "RB"},
    {name: "Shariatpur", code: "SP"},
    {name: "Tangail", code: "TG"},
    {name: "Bagerhat", code: "BG"},
    {name: "Chuadanga", code: "CD"},
    {name: "Jashore", code: "JS"},
    {name: "Jhenaidah", code: "JD"},
    {name: "Khulna", code: "KH"},
    {name: "kushtia", code: "KU"},
    {name: "Magura", code: "MA"},
    {name: "Meherpur", code: "MP"},
    {name: "Narail", code: "NL"},
    {name: "Satkhira", code: "SK"},
    {name: "Jamalpur", code: "JP"},
    {name: "Mymensingh", code: "MM"},
    {name: "Netrokona", code: "NK"},
    {name: "sherpur", code: "SH"},
    {name: "Bogura", code: "BO"},
    {name: "Jupurhat", code: "JH"},
    {name: "Naogaon", code: "NN"},
    {name: "Natore", code: "NT"},
    {name: "Chapai Nawabganj", code: "CN"},
    {name: "Pabna", code: "PB"},
    {name: "Rajshahi", code: "RJ"},
    {name: "Sirajganj", code: "SG"},
    {name: "Dinajpur", code: "DP"},
    {name: "Gaibandha", code: "GB"},
    {name: "Kurigram", code: "KG"},
    {name: "Lalmonirhat", code: "LL"},
    {name: "Nilphamari", code: "NP"},
    {name: "Panchagarh", code: "PG"},
    {name: "Rangpur", code: "RP"},
    {name: "Thakurgaon", code: "TG"},
    {name: "Habiganj", code: "HG"},
    {name: "Moulvibazar", code: "MB"},
    {name: "Sunamganj", code: "SM"},
    {name: "Sylhet", code: "Sy"},

]

export {districtsList};